config/routes.rb
Rails.application.routes.draw do

  # Defines the root path route ("/")
  root "kittens#index"

  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
# == Schema Information
#
# Table name: kittens
#
#  id         :bigint           not null, primary key
#  name       :string
#  age        :integer
#  cuteness   :integer
#  softness   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :update, :destroy]

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
    
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      redirect_to @kitten, notice: "kitten was successfuly saved"
    else
      render new_kitten_path, status: :unprocessable_entity, notice: 'Failed to save kitten to db'
    end
  end

  def edit
    
  end

  def update
    if @kitten.update(kitten_params)
      redirect_to @kitten, notice: 'Kitten was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @kitten.destroy
    redirect_to new_kitten_path, notice: 'Kitten was successfully destroyed.'
  end
  
  private
  def kitten_params
    params.require(:kitten).permit(:id, :name, :age, :cuteness, :softness)
  end

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten_form.html.erb
<%= form_with model: @kitten, class: "my-8 flex flex-col bg-cyan-50/50 border rounded max-w-xl min-w-80 py-5 px-4" do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :age %>
  <%= f.number_field :age %>
  <%= f.label :softness %>
  <%= f.number_field :softness %>
  <%= f.label :cuteness %>
  <%= f.number_field :cuteness %>
  <div class="flex justify-between">
    <%= f.submit class: "mt-2 btn-primary-md" %>
    <% if @kitten.persisted? %>
      <%= button_to "Show", kitten_path(@kitten), class: "mt-2 btn-primary-md" %>
    <% end %>
  </div>
<% end %>

app/views/kittens/_kittens_table.html.erb
<table class="py-5 px-4">
  <caption>All Kittens</caption>
  <thead>
    <tr class="rounded-t">
      <th class="border text-xl py-2 px-4">Name</th>
      <th class="border text-xl py-2 px-4">Age</th>
      <th class="border text-xl py-2 px-4">Cuteness</th>
      <th class="border text-xl py-2 px-4">Softness</th>
    </tr>
  </thead>
  <tbody>
    <% kittens.each do |kitten| %>
      <tr class="">
        <td class="border text-xl py-2 px-4"><%= link_to kitten.name, kitten_path(kitten.id), class: "" %></td>
        <td class="border text-xl py-2 px-4"><%= link_to kitten.age, kitten_path(kitten.id) %></td>
        <td class="border text-xl py-2 px-4"><%= link_to kitten.cuteness, kitten_path(kitten.id) %></td>
        <td class="border text-xl py-2 px-4"><%= link_to kitten.softness, kitten_path(kitten.id) %></td>
        <td class="text-xl flex py-2 px-4 justify-around">
          <%= link_to "Edit", edit_kitten_path(kitten.id), class: "btn-primary-sm text-center py-2 px-4" %>
          <%= button_to "Delete", kitten_path(kitten.id), method: :delete, data: { turbo: 'false', confirm: 'Are you sure?' }, class: "btn-primary-sm text-center py-2 px-4 ml-4" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/kittens/edit.html.erb
<div class="flex flex-col">
  <div>
    <h1 class="font-bold text-4xl">Kittens#edit</h1>
    <p>Find me in app/views/kittens/edit.html.erb</p>
  </div>

  <div>
    <%= render partial: 'kitten_form' %>
  </div>
</div>

app/views/kittens/index.html.erb
<div class="flex flex-col">
  <div class="">
    <h1 class="font-bold text-4xl">Kittens#index</h1>
  </div>

  <div class="my-8">
    <%= render partial: 'kittens_table', locals: { kittens: @kittens } %>
  </div>
</div>

app/views/kittens/new.html.erb
<div class="flex flex-col">
  <div>
    <h1 class="font-bold text-4xl">Kittens#new</h1>
    <p>Find me in app/views/kittens/new.html.erb</p>
  </div>

  <div>
    <%= render partial: 'kitten_form' %>
  </div>
</div>

app/views/kittens/show.html.erb
<div class="flex flex-col">
  <div class="">
    <h1 class="font-bold text-4xl">Kittens#show</h1>
  </div>

  <div class="my-8">
    <%= render partial: 'kittens_table', locals: { kittens: [@kitten] } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="">
      <nav class="">
        <% unless request.path == root_path %>
          <%= link_to 'All Kittens', kittens_path, class: "link" %>
        <% end %>
        <% unless request.path == new_kitten_path %>
          <%= link_to 'New Kitten', new_kitten_path, class: "link" %>
        <% end %>
      </nav>  
    </div>
    
    <div class='flash'>
      <p class='alert'><%= alert %></p>
      <p class='notice'><%= notice %></p>
    </div>

    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>